In [1]:
import numpy as np

In [2]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [13]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [3]:
a_list[3]

4

In [4]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [5]:
k_krotka[4]

5

In [8]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [9]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [13]:
n_array = np.array(a_list) # wektor numpy

In [14]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat', 100], dtype=object)

In [199]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [18]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [209]:
studenci_slownik["Zosia"]

22

In [19]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [23]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [24]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [30]:
studenci_slownik["Cuthulu"]= -1000000

In [31]:
studenci_slownik

{'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], 'Cuthulu': -1000000}

In [20]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [1]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

NameError: name 'studenci_slownik' is not defined

In [18]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [23]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [24]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [25]:
1 in a
"Igor" in studenci_slownik

True

In [207]:
print(a)

{'Franek', 1, 2, 3}


### Własne typy

In [7]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [8]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [3]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [4]:
pio_zajecia.ile_zajec

4

In [8]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [10]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [11]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [213]:
pio_zajecia.ile_mispow()

4

In [214]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [215]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [216]:
print(pio_zajecia.ile_zajec)

5


In [217]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [218]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [112]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [113]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [114]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

In [1]:
class NumerTelefonu():

    def __init__(self,numer):
        self.numer_tele = numer
        if len(self.numer_tele) == 9:
            print("Prawidlowy numer")
        else:
            print("Nieprawidłowy numer")

    def wojewodztwo(self):
        kierunkowy = self.numer_tele[0]+self.numer_tele[1]
        kierunkowe = {"42":"Lodz","43":"Sieradz","46":"Skierniewice"}
        try:
            kierunek = kierunkowe[kierunkowy]
        except KeyError:
            kierunek = "Komorkowy"
        return kierunek


    def __repr__(self):
        cyfry = ["zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć"]
        numer_do_stringa = []
        for cyfra in self.numer_tele:
            numer_do_stringa.append(cyfry[int(cyfra)])
        numer_do_stringa = ' '.join([str(cyfra) for cyfra in numer_do_stringa])
        return numer_do_stringa


W funkcji inicjalizującej sprawdzam czy numer telefonu poprawny sprawdzając jego długość, jeżeli nie zawiera 9 znaków uznaję go za błędny. Użytkownik jest informowany o obu przypadkach.

Drugą funkcją jaką utworzyłem jest województwo, choć w rzeczywistości numery kierunkowe nie odpowiadają aktualnym województwom, są powiązane jeszcze z poprzednim podziałem administracyjnym Polski. Na samym początku powstaje zmienna kierunek składająca sie z pierwszych dwóch elementów numeru.
słownik kierunkowe zawiera kilka kierunkowych, ponieważ wpisywanie wszystkich 49 kierunkowych.
Do sprawdzenia wykorzystuje obsługę wyjątków, ponieważ sprawdzam czy kierunek jest kluczem w słowniku, jeżeli nie to normalnie zwracało by bład ale zastosowanie except KeyError gwarantuje, ze program w przypadku tego błędu zwróci komunikat o tym, że numer jest komórkowy.

Ostatania funkcja jest to funkcja reprint, zamieniaja w sposob jaki bedzie printowana nasza klasa. Wykorzystuje liste stringów zawierajaca cyfry zapisane słownie, oraz liste numer do stringa, sluzaca do przechowywana numeru w postaci słownej. Funkcja for rozszerza liste numer do stringa o każdy element numeru zapisany słownie. Następnie wykorzstując "zrozumienie listy", aby przekształcić liste w numer zapisany słownie w postaci stringa.



In [2]:
numer_lodz = NumerTelefonu("466877868")

Prawidlowy numer


In [3]:
numer_lodz.wojewodztwo()

'Skierniewice'

In [4]:
print(numer_lodz)

cztery sześć sześć osiem siedem siedem osiem sześć osiem


In [49]:
#PONIŻEJ TESTOWE CELLE#
numer = "446877868"
cyfry = ["zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć"]
kierunkowy = numer[0]+numer[1]
number_to_str = ""
print(final)
for cyfra in numer:
    number_to_str = number_to_str + " " + cyfry[int(cyfra)]
print(number_to_str)
kierunkowe = {'42':'Lodz','43':'Sieradz','46':'Skierniewice'}
try:
    print(kierunkowe[kierunkowy])
except KeyError:
    print("Komorkowy")

['4', '4', '6', '8', '7', '7', '8', '6', '8']
 cztery cztery sześć osiem siedem siedem osiem sześć osiem
Komorkowy


In [33]:
cyfry = ["zero","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć"]
cos1 = "cos"
for cos in cyfry:
    print(cos)

zero
dwa
trzy
cztery
pięć
sześć
siedem
osiem
dziewięć
c
